시간으로 타이머 설정하는 기능 추가
hellodhlyn/webdo-bot pull request #3
Opened 2019-02-12 09:57 UTC by Jjungs7

2019-02-15 04:45 UTC, hellodhlyn requested changes
* 서버에서 동작 안함
* 로컬 테스트가 아닌 실제 환경에 맞는 유닛 테스트 코드를 추가해보아요

2019-02-15 04:45 UTC, HelloDHLyn commented on parsers.py
> +    _current_time = dt.datetime.now().strftime('%H:%M')
서버는 시간대가 UTC라 이 부분 정상 동작 안함.
예를 들어 22:00 으로 설정하면 한국 시각으로 13:00에 울린다던가 등등.

2019-02-15 04:45 UTC, HelloDHLyn commented on parsers.py
> +    is_time = True if match.group('is_time') == ':' else False
별건 아니고 요런 표현은
```python
is_time = (match.group('is_time') == ':')
```
으로 간소화 가능

2019-02-16 08:44 UTC, Jjungs7 commented on parsers.py
> +    is_time = True if match.group('is_time') == ':' else False
오호

2019-02-26 07:07 UTC, closed without merging

2019-02-26 07:08 UTC, Jjungs7 commented
new pull request on #6